name: ChatGames
version: '1.0'
author: 'RareHyperIon'
description: 'A plugin aimed to add fun chat based games to your server.'
main: me.RareHyperIon.ChatGames.ChatGames
api-version: 1.21
commands:
  chatgames:
    aliases: [chatgame, cg]
permissions:
  chatgames.reload:
    description: Allows the player to reload the ChatGames plugin
    default: op
